apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: slb
  labels:
    app: nginx-proxy
data:
  nginx.conf: |
    events {
      worker_connections 1024;
    }

    http {
      include /etc/nginx/conf.d/*.conf;
    }
