apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace/namespace.yaml
  - namespace/pv.yaml
  - namespace/pvc.yaml
  - ingress.yaml
  - dev/statefulset.yaml
  - dev/adapter-deployment.yaml
  - dev/adapter-service.yaml
  - dev/headless-service.yaml
  - dev/nginx-deployment.yaml
  - dev/nginx-service.yaml
  - dev/nginx-configmap.yaml
  - dev/taoskeeper-deployment.yaml
  - dev/taoskeeper-service.yaml
  - prod/statefulset.yaml
  - prod/adapter-deployment.yaml
  - prod/adapter-service.yaml
  - prod/headless-service.yaml
  - prod/nginx-deployment.yaml
  - prod/nginx-service.yaml
  - prod/nginx-configmap.yaml
  - prod/taoskeeper-deployment.yaml
  - prod/taoskeeper-service.yaml
