apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: observability
  labels:
    app: grafana
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus:9090
        isDefault: true
      - name: Loki
        type: loki
        access: proxy
        url: http://loki:3100
        jsonData:
          derivedFields:
            - name: "TraceID"
              matcherRegex: "traceID=(\\w+)"
              url: "$${__value.raw}"
              datasourceUid: tempo
      - name: Tempo
        type: tempo
        access: proxy
        url: http://tempo:3200
        uid: tempo
      - name: TDengine Dev
        type: tdengine-datasource
        access: proxy
        url: http://tdengine-dev-adapter.tdengine.svc:6041
        uid: tdengine-dev
        jsonData:
          user: root
        secureJsonData:
          url: http://tdengine-dev-adapter.tdengine.svc:6041
          password: taosdata
          basicAuth: cm9vdDp0YW9zZGF0YQ==
      - name: TDengine Prod
        type: tdengine-datasource
        access: proxy
        url: http://tdengine-prod-adapter.tdengine.svc:6041
        uid: tdengine-prod
        jsonData:
          user: root
        secureJsonData:
          url: http://tdengine-prod-adapter.tdengine.svc:6041
          password: taosdata
          basicAuth: cm9vdDp0YW9zZGF0YQ==
