apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: tdengine
  name: tdengine-nfs-root
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 500Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: tdengine-nfs-root
    namespace: tdengine
  nfs:
    path: /mnt/share/tdengine
    server: 192.168.2.105
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  volumeMode: Filesystem
