apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: emqx-certs
  namespace: emqx
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      app: emqx
      role: certs
  storageClassName: nfs
  volumeMode: Filesystem
