apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: emqx-data
  namespace: emqx
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      app: emqx
      role: data
  storageClassName: nfs
  volumeMode: Filesystem
