apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: observability
  labels:
    app: otel-collector
data:
  otel-collector.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: "0.0.0.0:4317"
          http:
            endpoint: "0.0.0.0:4318"

    processors:
      batch:
        send_batch_size: 1024
        send_batch_max_size: 2048
        timeout: 5s
      memory_limiter:
        check_interval: 5s
        limit_mib: 800
        spike_limit_mib: 200

    exporters:
      otlphttp/tempo:
        endpoint: "http://tempo:4318"
        sending_queue:
          queue_size: 1000
      otlphttp/loki:
        endpoint: "http://loki:3100/otlp"
        sending_queue:
          queue_size: 1000
      prometheus:
        endpoint: "0.0.0.0:8889"
        const_labels:
          cluster: k8s
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [otlphttp/tempo]
        metrics:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [prometheus]
        logs:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [otlphttp/loki]
