apiVersion: v1
kind: Service
metadata:
  name: taoskeeper-monitor
  namespace: tdengine
  labels:
    app: tdengine-monitor
    role: taoskeeper
spec:
  ports:
    - name: http
      port: 6043
      targetPort: 6043
  selector:
    app: tdengine-monitor
    role: taoskeeper
  type: ClusterIP
