apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: observability
  labels:
    app: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: "prometheus"
        static_configs:
          - targets: ["localhost:9090"]
      - job_name: "otel-collector"
        static_configs:
          - targets: ["otel-collector:8889"]
      - job_name: "emqx-prod"
        metrics_path: "/api/v5/prometheus/stats"
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names:
                - emqx
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app]
            action: keep
            regex: emqx
          - source_labels: [__meta_kubernetes_pod_label_cluster]
            action: keep
            regex: emqx-prod
          - source_labels: [__meta_kubernetes_pod_name]
            target_label: __address__
            replacement: "${1}.emqx-prod-headless.emqx.svc.cluster.local:18083"
          - source_labels: [__meta_kubernetes_pod_name]
            target_label: instance
          - source_labels: [__meta_kubernetes_pod_label_cluster]
            target_label: emqx_cluster
      - job_name: "emqx-k8s-prod"
        metrics_path: "/api/v5/prometheus/stats"
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names:
                - emqx
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app]
            action: keep
            regex: emqx
          - source_labels: [__meta_kubernetes_pod_label_cluster]
            action: keep
            regex: k8s-prod
          - source_labels: [__meta_kubernetes_pod_name]
            target_label: __address__
            replacement: "${1}.emqx-headless.emqx.svc.cluster.local:18083"
          - source_labels: [__meta_kubernetes_pod_name]
            target_label: instance
          - source_labels: [__meta_kubernetes_pod_label_cluster]
            target_label: emqx_cluster
      - job_name: "tdengine-dev"
        static_configs:
          - targets:
              - "taoskeeper-dev.tdengine.svc:6043"
            labels:
              tdengine_role: "taoskeeper"
      - job_name: "tdengine-prod"
        static_configs:
          - targets:
              - "taoskeeper-prod.tdengine.svc:6043"
            labels:
              tdengine_role: "taoskeeper"
