apiVersion: v1
kind: ConfigMap
metadata:
  name: tdengine-dev-nginx-conf
  namespace: tdengine
  labels:
    app: tdengine-dev
    role: nginx
data:
  nginx.conf: |
    user nginx;
    worker_processes auto;
    error_log /var/log/nginx/error.log warn;
    pid /var/run/nginx.pid;

    events {
        worker_connections 1024;
    }

    stream {
        upstream taosadapter-udp {
            server tdengine-dev-adapter.tdengine.svc.cluster.local:6044;
        }

        server {
            listen 6044 udp;
            proxy_pass taosadapter-udp;
            proxy_timeout 300s;
        }
    }
