apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tdengine-prod
    role: adapter
  name: tdengine-prod-adapter
  namespace: tdengine
spec:
  progressDeadlineSeconds: 600
  replicas: 4
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: tdengine-prod
      role: adapter
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: tdengine-prod
        role: adapter
    spec:
      containers:
        -
          command:
            - taosadapter
          env:
            -
              name: TAOS_FIRST_EP
              value: tdengine-prod-0.tdengine-prod-headless.tdengine.svc.cluster.local:6030
            -
              name: TAOS_SECOND_EP
              value: tdengine-prod-1.tdengine-prod-headless.tdengine.svc.cluster.local:6030
            -
              name: TAOS_SML_CHILD_TABLE_NAME
              value: tname
            -
              name: TAOS_ADAPTER_MONITOR_DISABLE
              value: "false"
            -
              name: TAOS_ADAPTER_UPLOAD_KEEPER_URL
              value: "http://taoskeeper-prod.tdengine.svc.cluster.local:6043/adapter_report"
            -
              name: TAOS_ADAPTER_DEBUG
              value: "false"
            -
              name: TAOS_DEBUG_FLAG
              value: "0"
            -
              name: TAOS_ADAPTER_LOG_LEVEL
              value: "info"
            -
              name: TAOS_ADAPTER_LOG_KEEP_DAYS
              value: "1"
            -
              name: TAOS_ADAPTER_LOG_ROTATION_SIZE
              value: "134217728"
            -
              name: TAOS_SML_WORKER
              value: "16"
            -
              name: TAOS_SML_BATCH_SIZE
              value: "10000"
            -
              name: TAOS_SML_FLUSH_INTERVAL
              value: "5s"
          image: tdengine/tdengine:3.3.6.13
          imagePullPolicy: IfNotPresent
          name: taosadapter
          ports:
            -
              containerPort: 6041
              name: tcp-rest
              protocol: TCP
            -
              containerPort: 6044
              name: udp-native
              protocol: UDP
          resources:
            limits:
              cpu: 2
              memory: 2Gi
            requests:
              cpu: 200m
              memory: 512Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            -
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: tdengine-prod
                    role: adapter
                topologyKey: kubernetes.io/hostname
              weight: 100
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
