apiVersion: v1
kind: Service
metadata:
  labels:
    app: tdengine-prod
    role: adapter
  name: tdengine-prod-adapter
  namespace: tdengine
spec:
  ports:
    -
      name: tcp-rest
      port: 6041
      protocol: TCP
      targetPort: 6041
    -
      name: udp-native
      port: 6044
      protocol: UDP
      targetPort: 6044
  selector:
    app: tdengine-prod
    role: adapter
  type: ClusterIP
