apiVersion: v1
kind: Service
metadata:
  labels:
    app: tdengine-prod
    role: nginx
  name: tdengine-prod-nginx
  namespace: tdengine
spec:
  externalTrafficPolicy: Cluster
  ports:
    - name: udp-native
      nodePort: 30074
      port: 6044
      protocol: UDP
      targetPort: 6044
  selector:
    app: tdengine-prod
    role: nginx
  type: NodePort
