apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempo
  namespace: observability
  labels:
    app: tempo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tempo
  template:
    metadata:
      labels:
        app: tempo
    spec:
      containers:
        - name: tempo
          image: grafana/tempo:main-40b985c-amd64
          args:
            - "--target=all"
            - "--config.file=/etc/tempo/tempo.yaml"
          ports:
            - containerPort: 3200
              name: http
              protocol: TCP
            - containerPort: 4317
              name: otlp-grpc
              protocol: TCP
            - containerPort: 4318
              name: otlp-http
              protocol: TCP
            - containerPort: 14250
              name: jaeger-grpc
              protocol: TCP
            - containerPort: 14268
              name: jaeger-http
              protocol: TCP
            - containerPort: 9411
              name: zipkin
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /etc/tempo
            - name: data
              mountPath: /var/tempo
              subPath: tempo
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "2Gi"
              cpu: "500m"
      volumes:
        - name: config
          configMap:
            name: tempo-config
        - name: data
          persistentVolumeClaim:
            claimName: shared-nfs
      nodeSelector:
        kubernetes.io/arch: amd64
