apiVersion: v1
kind: Service
metadata:
  name: emqx-prod-headless
  namespace: emqx
  labels:
    app: emqx
    cluster: emqx-prod
spec:
  clusterIP: None
  ports:
    - name: ekka
      port: 4370
      targetPort: 4370
    - name: dashboard
      port: 18083
      targetPort: 18083
  selector:
    app: emqx
    cluster: emqx-prod
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: emqx-prod
  namespace: emqx
  labels:
    app: emqx
    cluster: emqx-prod
spec:
  ports:
    - name: mqtt
      port: 1883
      targetPort: 1883
  selector:
    app: emqx
    cluster: emqx-prod
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: emqx-prod-nodeport
  namespace: emqx
  labels:
    app: emqx
    cluster: emqx-prod
spec:
  ports:
    - name: mqtt
      port: 1883
      targetPort: 1883
      nodePort: 31783
    - name: dashboard
      port: 18083
      targetPort: 18083
      nodePort: 31983
    - name: ws
      port: 8083
      targetPort: 8083
      nodePort: 30783
    - name: wss
      port: 8084
      targetPort: 8084
      nodePort: 30784
  selector:
    app: emqx
    cluster: emqx-prod
  type: NodePort
