---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cmd-params-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cmd-params-cm
  namespace: argocd
data:
  server.insecure: "true"
  application.resync.period: "60"
  reposerver.repo.cache.expiration: "3m"
  controller.status.processors: "20"
  controller.operation.processors: "10"
