---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-secret
  namespace: argocd
spec:
  encryptedData:
    repository.credentials: AgBnEgV0g+7glfcaSh8ebjsRQ2cX/lSEv/HPivt/ke5xXKL6BoNIQBTR37eQiOsPkdWFBGZp05N5wgG1EYax5OWmgSbL9BTU6psO0PW2pyvGYoCL05SkmNMtcOfIDgfoD565rFdRYv92AYrJv6Vb5v/46CulyAVEKRa883ZQhvFPlcssgd6T+x4wSu57oXd5PRFNKFFsJnzZVvKQRFjYu17gRiXn66viz80f+PE4U6V7mfrCB8Moo/yamcG709tOKH9JzqFbXZOtBheYwCOlhDdgXBlvP0Z8a0sNgRwpPY0PTorZw9MXSNcWdSpyx6eAlMs52elEHBmx1CRfUKBXVI2YZIfmCiCqi/uI3+whHES34+Zus2oPCr1z29X1V73IkS5ZtRM+xAslcbcq7R5R1v64DFC7POf8yAiL6tLeDvWf7JnkI369UHeCzS2Rj7tK/lpRV5CuQxQUwINoGcbs6H/NWJpmWRTthp7SgltQl104A3T+Mm7iiV329YItLN/IupLbz4BJwCAGug4dsqnT7P6383YjFqIneqHqv/47xbxFrv6buh4mOoOcE3vvHWz+qT6dvuU+bMVgognn6i4dQLGW2rgTfBWPoiS79UTHjHazVK79zOppalFHRQ140fVX2EhPJ9q/8S6nlI/IfjprTJGla5Fe9WBUKXq56blzv1w6ZuQhDHtqpp/AVHFZ/8x2Rx9x48Jwsy4kBOcFzGCAxfd1psIE+FYj8GLDMG1emdBY0m0IhTLq7glVIorxyE7X6mT0kKDZ5QsNOTdjz8QYIrBP7UgA1iPSNk/FbEDI6L19IdeCYQBtQk3S6+tNOXWfir4Uc0Hxeezlg+9VI54ttgsKx27hm60H0ux4efdRgyBCqEkjgU8LfTaOA1aXGWXQS4sZUI4xIjXiqs5NMS3SDuHyTZpifD7mBu7hxwSxjpEoGBybZiu5Jsz0R1plGj22bpqYOpQlv4yWOUvmRBaJMcdT52BnMWut3gq67ecx1criUzPz+gGUSf376OLpdr220tiueYdLmdF3O18bXlQKe1HAWxNYaw8ou8RSmytfngrDUjNZKKHOgoSDqy1ylT0CsX0XyPErdqfjtBg79hGzfCFSb+1pAgRSMyEzxsbcwiZad7MMcJJHv22hxGvAufcKcpyqUjPhBhteNA0zdPgSsDusPL3wnFKE7LV5MA9PSsO/1TrRQIZryPFHNIdVSqEkYWL9HekknttrDFhYYxjyjgOgv8rVzGP55I4GfdftmgTYsB6wsyePmsF7YETXEjiXG3YIhKl/HTagwgv8XeYAVA+uojQ/W+vqiCVg4IgvZppJJqXSnmASKfWFpdCXzHeEKIQ=
  template:
    metadata:
      labels:
        app.kubernetes.io/name: argocd-secret
        app.kubernetes.io/part-of: argocd
      name: argocd-secret
      namespace: argocd
    type: Opaque
