apiVersion: v1
kind: PersistentVolume
metadata:
  name: new-api-nfs
  labels:
    app: new-api
    type: nfs
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.2.105
    path: /mnt/share/k8s/new-api
