apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-nfs
  namespace: new-api
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeName: shared-nfs
