apiVersion: v1
kind: Service
metadata:
  name: emqx-test-headless
  namespace: emqx
  labels:
    app: emqx
    cluster: k8s-test
spec:
  clusterIP: None
  ports:
    - name: mqtt
      port: 1883
      targetPort: 1883
    - name: dashboard
      port: 18083
      targetPort: 18083
    - name: ekka
      port: 4370
      targetPort: 4370
  selector:
    app: emqx
    cluster: k8s-test
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: emqx-test-nodeport
  namespace: emqx
  labels:
    app: emqx
    cluster: k8s-test
spec:
  ports:
    - name: mqtt
      port: 1883
      targetPort: 1883
      nodePort: 31884
    - name: dashboard
      port: 18083
      targetPort: 18083
      nodePort: 31084
    - name: ws
      port: 8083
      targetPort: 8083
      nodePort: 30885
    - name: wss
      port: 8084
      targetPort: 8084
      nodePort: 30886
  selector:
    app: emqx
    cluster: k8s-test
  type: NodePort
