apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nession-staging
  namespace: argocd
  labels:
    app: nession-staging
spec:
  project: default
  source:
    repoURL: https://github.com/bestnathan/nession.git
    targetRevision: main
    path: k8s/overlays/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: nession
  revisionHistoryLimit: 10
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
      limit: 5
    syncOptions:
    - CreateNamespace=true
    - PruneLast=true
    - ApplyOutOfSyncOnly=true
