apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace/namespace.yaml
  - namespace/pv.yaml
  - namespace/pvc.yaml
  - emqx/service.yaml
  - emqx/statefulset.yaml
  - emqx-test/service.yaml
  - emqx-test/statefulset.yaml
  - ingress.yaml
