apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace/namespace.yaml
  - namespace/pv.yaml
  - namespace/pvc.yaml
  - emqx-prod/service.yaml
  - emqx-prod/statefulset.yaml
  - k8s-prod/service.yaml
  - k8s-prod/statefulset.yaml
  - ingress.yaml
