apiVersion: v1
kind: Service
metadata:
  name: emqx-headless
  namespace: emqx
  labels:
    app: emqx
spec:
  clusterIP: None
  ports:
    - name: mqtt
      port: 1883
      targetPort: 1883
    - name: dashboard
      port: 18083
      targetPort: 18083
  selector:
    app: emqx
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: emqx-nodeport
  namespace: emqx
  labels:
    app: emqx
spec:
  ports:
    - name: mqtt
      port: 1883
      targetPort: 1883
      nodePort: 31883
    - name: dashboard
      port: 18083
      targetPort: 18083
      nodePort: 31083
    - name: ws
      port: 8083
      targetPort: 8083
      nodePort: 30883
    - name: wss
      port: 8084
      targetPort: 8084
      nodePort: 30884
  selector:
    app: emqx
  type: NodePort
