apiVersion: v1
kind: PersistentVolume
metadata:
  name: emqx-certs-slbbox-nfs
  labels:
    app: slb
    type: nfs
    purpose: emqx-certs
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.2.105
    path: /mnt/share/k8s/emqx/certs
  storageClassName: nfs
  volumeMode: Filesystem
