apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: emqx-certs
  namespace: slb
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      purpose: emqx-certs
  storageClassName: nfs
  volumeMode: Filesystem
