apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace/namespace.yaml
  - namespace/pv.yaml
  - namespace/pvc.yaml
  - new-api/deployment.yaml
  - new-api/service.yaml
  - new-api/ingress.yaml
  - postgres/deployment.yaml
  - postgres/service.yaml
  - redis/deployment.yaml
  - redis/service.yaml
