apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: new-api
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          env:
            - name: POSTGRES_USER
              value: "root"
            - name: POSTGRES_PASSWORD
              value: "123456"
            - name: POSTGRES_DB
              value: "new-api"
          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
              subPath: new-api/postgres
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: shared-nfs
